[versions]
# Application
agp = "8.13.0"

# Kotlin
kotlin = "2.3.0"

# Kotlin jvm
jetbrainsKotlinJvm = "2.3.0"

# Core
coreKtx = "1.17.0"

# Activity compose
activityCompose = "1.12.2"

# Compose bom
composeBom = "2026.01.00"

# Compose runtime
runtime = "1.10.1"

# Material 3
material3Android = "1.5.0-alpha12"

# Hilt
hiltAndroid = "2.58"
hiltNavigationCompose = "1.3.0"

# Navigation & serialization
composeNavigation = "2.9.6"
serialization = "1.9.0"

# Room
roomKtx = "2.8.4"

# Coil
coilCompose = "2.7.0"

# Ksp
kspPlugin = "2.3.0"

# Paging
pagingCompose = "3.3.6"

# Lottie
lottie = "6.7.1"

# Splashscreen
coreSplashscreen = "1.2.0"

# Haze
hazeMaterials = "1.6.6"

# Datastore
datastorePreferences = "1.2.0"

# Compose animation graphics
animationGraphics = "1.10.1"

# Retrofit
retrofit = "3.0.0"
converterGson = "3.0.0"

# Exo player
media3 = "1.9.0"

# Material
material = "1.10.1"

# Lifecycle ViewModel
lifecycleViewmodelKtx = "2.10.0"

# Testing
mockk = "1.14.7"
junit = "4.13.2"
coroutinesTest = "1.10.2"
turbine = "1.2.1"


[libraries]
# Core
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }

# Activity compose
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }

# Compose bom
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }

# Compose runtime
androidx-compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "runtime" }

# Material 3
androidx-material3-android = { module = "androidx.compose.material3:material3-android", version.ref = "material3Android" }

# Room
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomKtx" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomKtx" }

# Hilt
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltAndroid" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }

# Naivation & serialization
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization"}
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "composeNavigation" }

# Coil
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }

# Paging
androidx-paging-compose = { module = "androidx.paging:paging-compose", version.ref = "pagingCompose" }
androidx-paging-runtime-ktx = { module = "androidx.paging:paging-runtime-ktx", version.ref = "pagingCompose" }

# Lottie
lottie = { module = "com.airbnb.android:lottie-compose", version.ref = "lottie" }

# Splashscreen
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }

# Haze
haze-materials = { module = "dev.chrisbanes.haze:haze-materials", version.ref = "hazeMaterials" }

# Datastore
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }

# Compose animation graphics
androidx-animation-graphics = { module = "androidx.compose.animation:animation-graphics", version.ref = "animationGraphics" }

# Media 3
androidx-media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3" }
androidx-media3-exoplayer-hls = { module = "androidx.media3:media3-exoplayer-hls", version.ref = "media3" }
androidx-media3-ui = { module = "androidx.media3:media3-ui-compose", version.ref = "media3" }

# Retrofit
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGson" }

# Material
androidx-material = { module = "androidx.compose.material:material", version.ref = "material" }

# Compose debug
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }

# Lifecycle ViewModel
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }

# Unit tests
junit = { group = "junit", name = "junit", version.ref = "junit" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutinesTest" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }

# Android tests
mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockk" }
androidx-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version = "androidxTestExtJunit" }


[plugins]
# Application
android-application = { id = "com.android.application", version.ref = "agp" }

# Kotlin
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

# Kotlin jvm
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }

# Compose compiler
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

# Serialization
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

# Hilt
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hiltAndroid" }

# Ksp
ksp = { id = "com.google.devtools.ksp", version.ref = "kspPlugin" }

# Android
android-library = { id = "com.android.library", version.ref = "agp" }